### ISSUE TITLE
Chapter 02 - plotting

### ISSUE THREAD

**Issue by Eraseri** [PacktPublishing/Interpretable-Machine-Learning-with-Python#4]
Hi,

On following part of book I get error down below

`plt.rcParams.update({'font.size': 14})
fig, axarr = plt.subplots(2, 2, figsize=(12,8), sharex=True, sharey=False)
mldatasets.create_decision_plot(X_test, y_test, log_result, [5, 1], ['ap_hi [mmHg]', 'age [years]'], 
                     X_highlight, filler_feature_values, filler_feature_ranges, ax=axarr.flat[0])
mldatasets.create_decision_plot(X_test, y_test, log_result, [5, 7], ['ap_hi [mmHg]', 'cholesterol [1-3]'], 
                     X_highlight, filler_feature_values, filler_feature_ranges, ax=axarr.flat[1])
mldatasets.create_decision_plot(X_test, y_test, log_result, [5, 6], ['ap_hi [mmHg]', 'ap_lo [mmHg]'], 
                     X_highlight, filler_feature_values, filler_feature_ranges, ax=axarr.flat[2])
mldatasets.create_decision_plot(X_test, y_test, log_result, [5, 4], ['ap_hi [mmHg]', 'weight [kg]'], 
                     X_highlight, filler_feature_values, filler_feature_ranges, ax=axarr.flat[3])
plt.subplots_adjust(top = 1, bottom=0, hspace=0.2, wspace=0.2)
plt.show()`

`
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-22-bc55c8d57ee3> in <module>
      1 plt.rcParams.update({'font.size': 14})
      2 fig, axarr = plt.subplots(2, 2, figsize=(12,8), sharex=True, sharey=False)
----> 3 mldatasets.create_decision_plot(X_test, y_test, log_result, [5, 1], ['ap_hi [mmHg]', 'age [years]'], 
      4                      X_highlight, filler_feature_values, filler_feature_ranges, ax=axarr.flat[0])
      5 mldatasets.create_decision_plot(X_test, y_test, log_result, [5, 7], ['ap_hi [mmHg]', 'cholesterol [1-3]'], 

c:\users\***\miniconda3\lib\site-packages\machine_learning_datasets\common.py in create_decision_plot(X, y, model, feature_index, feature_names, X_highlight, filler_feature_values, filler_feature_ranges, ax)
    399     filler_values = dict((k, filler_feature_values[k]) for k in filler_feature_values.keys() if k not in feature_index)
    400     filler_ranges = dict((k, filler_feature_ranges[k]) for k in filler_feature_ranges.keys() if k not in feature_index)
--> 401     ax = plot_decision_regions(sm.add_constant(X).to_numpy(), y.to_numpy(), clf=model, 
    402                           feature_index=feature_index,
    403                           X_highlight=X_highlight,

c:\users\***\miniconda3\lib\site-packages\mlxtend\plotting\decision_regions.py in plot_decision_regions(X, y, clf, feature_index, filler_feature_values, filler_feature_ranges, ax, X_highlight, res, legend, hide_spines, markers, colors, scatter_kwargs, contourf_kwargs, scatter_highlight_kwargs)
    242                antialiased=True)
    243 
--> 244     ax.axis(xmin=xx.min(), xmax=xx.max(), y_min=yy.min(), y_max=yy.max())
    245 
    246     # Scatter training data samples

c:\users\***\miniconda3\lib\site-packages\matplotlib\axes\_base.py in axis(self, emit, *args, **kwargs)
   1933             self.set_ylim(ymin, ymax, emit=emit, auto=yauto)
   1934         if kwargs:
-> 1935             raise TypeError(f"axis() got an unexpected keyword argument "
   1936                             f"'{next(iter(kwargs))}'")
   1937         return (*self.get_xlim(), *self.get_ylim())

TypeError: axis() got an unexpected keyword argument 'y_min'
`

**Comment by smasis001** [comment]
Hi Eraseri,

What version of matplotlib did you install? This seems to be an issue that affects matplotlib 3.3 and above, while using mlxtend 0.14.0. As proof that it works with the right versions of each library check out the Google Colab (https://colab.research.google.com/drive/1CiUPbK_xgXFq6735O320a_3GUiuY4XGZ?usp=sharing). You can either downgrade matplotlib to the version in the requirements.txt (3.2.2) or upgrade mlxtend to latest version (0.18.0) - I haven't tried this last suggestion but it says here that it fixes it: https://github.com/rasbt/mlxtend/issues/735.  Let me know if you need more help with that.

**Comment by Eraseri** [comment]
I have matplotlib version 3.4.1.

I tried installing mlxtend to latest version 0.18.0 from 0.14.0. This however doesn't work as machine learning datasets is not compatible with 0.18.0 and I get other problems. I have to try out something else...

**Comment by Eraseri** [comment]
Yap. Got it working with matplotlib 3.2.2. Thanks.
